const modules=[
{title:'Problem Solving',topics:[['1.1','Demonstrate Programming Life Cycle (PLC)','The Programming Life Cycle includes problem definition, analysis, design, coding, testing, documentation and maintenance.','Example: For a grade calculator, identify inputs (marks), processing (calculate grade), and output (grade).'],['1.2','Construct problem solving concept','Break a problem into input, process and output (IPO). Use decomposition to solve smaller tasks.','IPO example: Input = two numbers; Process = addition; Output = sum.'],['1.3','Construct the different types of algorithms, pseudocode and flowcharts in solve problem','An algorithm is a finite series of instructions. Pseudocode uses structured plain language; flowcharts use standard symbols such as oval (start/end), parallelogram (input/output), rectangle (process), and diamond (decision).','START\nINPUT a, b\nsum ← a + b\nOUTPUT sum\nEND']]},
{title:'Introduction to Fundamentals of Programming',topics:[['2.1','Construct the C++ program basic structure','A basic C++ program uses #include, main(), statements and return 0.',' #include <iostream>\nusing namespace std;\nint main() {\n  cout << "Hello World";\n  return 0;\n}'],['2.2','Construct identifier and data types','Identifiers name variables and functions. Common C++ data types include int, double, char, bool and string.','int age = 18;\ndouble price = 12.50;\nchar grade = \'A\';\nbool passed = true;'],['2.3','Follow the basic step of computer program','Plan the solution, write source code, compile, run and test with different inputs.','Source code → Compiler → Executable → Run → Test'],['2.4','Follow instruction process of compiling and debugging process and errors in programming','Syntax errors violate language rules; runtime errors happen during execution; logic errors produce wrong results. Debugging identifies and corrects them.','Example syntax error: cout << "Hi"  // missing semicolon']]},
{title:'Program Elements',topics:[['3.1','Construct Identifiers','Use meaningful variable names. C++ identifiers cannot begin with a digit, contain spaces or use reserved keywords.','int totalMarks = 90;\n// 2marks and total marks are invalid identifiers'],['3.2','Construct operators and expressions','Arithmetic (+, -, *, /, %), relational (==, !=, >, <, >=, <=), and logical (&&, ||, !) operators form expressions.','int total = 10 + 5;\nbool eligible = (total >= 10) && (total < 20);'],['3.3','Construct input output statements','Use cin to read keyboard input and cout to display output.','int age;\ncout << "Enter age: ";\ncin >> age;\ncout << "Age: " << age;']]},
{title:'Program Control Structure',topics:[['4.1','Construct program control structure','Control structures determine execution order: sequence, selection and repetition.','Sequence: input → calculate → display'],['4.2','Construct selection control structures in problem solving','Use if, if-else or switch to choose actions based on conditions.','if (mark >= 50) {\n  cout << "Pass";\n} else {\n  cout << "Fail";\n}'],['4.3','Construct loops control structure in problem solving','Use for, while or do-while to repeat instructions. Ensure loop conditions eventually terminate.','for (int i = 1; i <= 5; i++) {\n  cout << i << endl;\n}']]},
{title:'Array',topics:[['5.1','Construct array in programming','An array stores multiple values of the same type under one name. C++ array indices start at 0.','int marks[3] = {70, 80, 90};\ncout << marks[0]; // 70\nfor (int i = 0; i < 3; i++) {\n  cout << marks[i] << endl;\n}']]},
{title:'Function',topics:[['6.1','Build functions in programming','A function groups reusable instructions. It may return a value or use void for no return value.','int add(int a, int b) {\n  return a + b;\n}'],['6.2','Build function prototype','A prototype declares a function name, return type and parameter types before its definition.','int add(int a, int b);\nint main() {\n  cout << add(2, 3);\n}\nint add(int a, int b) { return a + b; }'],['6.3','Build parameters passing techniques','Pass by value copies the argument; pass by reference (&) lets a function modify the original variable.','void increase(int &x) {\n  x++;\n}\nint number = 5;\nincrease(number); // number becomes 6']]}];

// Modul 1: nota dwibahasa, rajah, latihan dan aktiviti pengukuhan.
const richModule1 = [
`<div class="learning"><h3>Learning Outcomes / Hasil Pembelajaran</h3><p>Explain and demonstrate each phase of the Programming Life Cycle (PLC). / Terangkan dan tunjukkan setiap fasa kitar hayat pengaturcaraan.</p><h3>What is PLC? / Apakah PLC?</h3><p>The PLC is a systematic process for developing reliable programs. / PLC ialah proses sistematik untuk membangunkan program yang boleh dipercayai.</p><ol><li><b>Problem definition / Kenal pasti masalah:</b> Determine what must be solved and expected results.</li><li><b>Analysis / Analisis:</b> Identify inputs, processing, outputs and constraints.</li><li><b>Design / Reka bentuk:</b> Plan an algorithm, pseudocode or flowchart.</li><li><b>Coding / Pengekodan:</b> Translate the design into C++ statements.</li><li><b>Testing & debugging / Pengujian:</b> Test cases and fix errors.</li><li><b>Documentation / Dokumentasi:</b> Record usage, design and maintenance notes.</li><li><b>Maintenance / Penyelenggaraan:</b> Update and improve after deployment.</li></ol><div class="process-flow"><span>Define</span><b>→</b><span>Analyse</span><b>→</b><span>Design</span><b>→</b><span>Code</span><b>→</b><span>Test</span><b>→</b><span>Document & Maintain</span></div><h3>Case Study / Kajian Kes</h3><p><b>Student Grade Calculator:</b> Accept a mark from 0–100 and display PASS for marks of 50 or above, otherwise FAIL. / Terima markah 0–100 dan paparkan LULUS jika 50 ke atas, selainnya GAGAL.</p><div class="task"><b>Activity 1 / Aktiviti 1</b><p>List the input, output and two test cases (e.g., 49 and 50). State what should happen for an invalid mark of 110. / Senaraikan input, output dan dua kes ujian. Nyatakan tindakan bagi markah tidak sah 110.</p></div></div>`,
`<div class="learning"><h3>Learning Outcomes / Hasil Pembelajaran</h3><p>Apply input–process–output (IPO), decomposition and step-by-step reasoning to solve a problem. / Gunakan IPO, pecahan masalah dan penaakulan berlangkah.</p><h3>Problem-solving steps / Langkah penyelesaian masalah</h3><ol><li>Read the problem carefully / Baca masalah dengan teliti.</li><li>Identify the required inputs / Kenal pasti input.</li><li>Determine calculations or decisions / Tentukan proses.</li><li>Identify outputs / Kenal pasti output.</li><li>Test with sample data / Uji menggunakan data contoh.</li></ol><h3>IPO Chart / Jadual IPO</h3><table class="ipo"><thead><tr><th>Input</th><th>Process</th><th>Output</th></tr></thead><tbody><tr><td>price, quantity</td><td>total = price × quantity</td><td>total payment</td></tr></tbody></table><p><b>Worked example / Contoh:</b> Price RM8, quantity 3 → total RM24. / Harga RM8, kuantiti 3 → jumlah RM24.</p><h3>Decomposition / Pecahan masalah</h3><p>Divide a large task into smaller tasks: read values → validate inputs → calculate → display result. / Pecahkan tugasan besar kepada beberapa tugasan kecil.</p><div class="task"><b>Activity 2 / Aktiviti 2</b><p>Create an IPO table for calculating the average of three quiz marks. / Bina jadual IPO untuk mengira purata tiga markah kuiz.</p><details><summary>Show suggested answer / Lihat cadangan jawapan</summary><p>Input: m1, m2, m3. Process: average = (m1 + m2 + m3) / 3. Output: average.</p></details></div></div>`,
`<div class="learning"><h3>Learning Outcomes / Hasil Pembelajaran</h3><p>Construct algorithms using sequence, selection and repetition, and represent them in pseudocode and flowcharts. / Bina algoritma jujukan, pilihan dan ulangan dalam pseudokod serta carta alir.</p><h3>Algorithm / Algoritma</h3><p>A finite set of unambiguous steps to solve a problem. / Satu set langkah jelas dan terhingga untuk menyelesaikan masalah.</p><h3>Three control patterns / Tiga struktur asas</h3><ul><li><b>Sequence / Jujukan:</b> Instructions run in order.</li><li><b>Selection / Pilihan:</b> IF–ELSE chooses a path.</li><li><b>Repetition / Ulangan:</b> WHILE or FOR repeats steps.</li></ul><h3>Flowchart symbols / Simbol carta alir</h3><div class="symbols"><div><span class="oval">START / END</span><small>Terminator</small></div><div><span class="parallelogram">INPUT / OUTPUT</span><small>Data</small></div><div><span class="rectangle">PROCESS</span><small>Process</small></div><div><span class="diamond">DECISION?</span><small>Decision</small></div></div><h3>Example: Pass or Fail / Contoh: Lulus atau Gagal</h3><pre><code>START
INPUT mark
IF mark &gt;= 50 THEN
    OUTPUT "PASS"
ELSE
    OUTPUT "FAIL"
ENDIF
END</code></pre><div class="flow-example"><span class="oval">START</span><b>↓</b><span class="parallelogram">INPUT mark</span><b>↓</b><span class="diamond">mark ≥ 50?</span><div class="branches"><span>YES → PASS</span><span>NO → FAIL</span></div><b>↓</b><span class="oval">END</span></div><div class="task"><b>Activity 3 / Aktiviti 3</b><p>Write pseudocode and draw a flowchart that checks whether a number is even or odd. / Tulis pseudokod dan lukis carta alir untuk menentukan nombor genap atau ganjil.</p><details><summary>Hint / Petunjuk</summary><p>Use remainder: number MOD 2 = 0 means EVEN; otherwise ODD.</p></details></div></div>`
];

const questions=[
[{q:'Which stage normally comes before coding?',a:['Maintenance','Design','Deployment'],correct:1},{q:'Which flowchart symbol represents a decision?',a:['Diamond','Oval','Rectangle'],correct:0},{q:'IPO stands for...',a:['Input Process Output','Index Program Object','Internal Print Order'],correct:0}],
[{q:'What is the entry point of a typical C++ program?',a:['start()','main()','begin()'],correct:1},{q:'Which data type stores a whole number?',a:['int','char','bool'],correct:0},{q:'A missing semicolon is usually a...',a:['Logic error','Syntax error','Hardware error'],correct:1}],
[{q:'Which is a valid C++ identifier?',a:['2score','total_score','total score'],correct:1},{q:'Which operator checks equality?',a:['=','==','!='],correct:1},{q:'Which statement reads input?',a:['cin >> age;','cout << age;','return age;'],correct:0}],
[{q:'Which statement handles two alternative branches?',a:['if-else','include','return'],correct:0},{q:'Which loop is commonly used for a known number of repetitions?',a:['for','switch','if'],correct:0},{q:'Which is a selection structure?',a:['while','switch','for'],correct:1}],
[{q:'What is the first index of a C++ array?',a:['1','0','-1'],correct:1},{q:'How many values can int a[5] store?',a:['4','5','6'],correct:1},{q:'Which accesses the third array element?',a:['a[3]','a[2]','a(3)'],correct:1}],
[{q:'Which keyword declares a function with no return value?',a:['void','int','break'],correct:0},{q:'What does a function prototype provide?',a:['Declaration','Loop execution','Array index'],correct:0},{q:'Which syntax denotes a reference parameter?',a:['int x','int &x','int * x = 0'],correct:1}]
];
let selected=0;const $=id=>document.getElementById(id);const key=i=>'pf-progress-'+i;function completed(i){return localStorage.getItem(key(i))==='1'}
function nav(){ $('nav').innerHTML=modules.map((m,i)=>`<button class="navitem ${i===selected?'active':''}" data-module="${i}"><span>${String(i+1).padStart(2,'0')} · ${m.title}</span><span>${completed(i)?'✓':''}</span></button>`).join('');document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>show(+b.dataset.module));}
function home(){selected=-1;nav();$('content').innerHTML=`<div class="hero"><div class="eyebrow">E-LEARNING TVET · C++</div><h1>Programming Fundamentals</h1><p>Belajar asas pengaturcaraan secara berperingkat: penyelesaian masalah, struktur C++, elemen program, kawalan, array dan function.</p><button class="primary" id="start">Mula Belajar →</button></div><h2>Modul Pembelajaran</h2><div class="cards">${modules.map((m,i)=>`<button class="course" data-go="${i}"><span class="eyebrow">MODUL ${i+1} ${completed(i)?' · ✓ Selesai':''}</span><strong>${m.title}</strong><small>${m.topics.length} subtopik · Nota & kuiz</small><span class="arrow">Buka modul →</span></button>`).join('')}</div>`;$('start').onclick=()=>show(0);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(+b.dataset.go));}
function show(i){selected=i;nav();let m=modules[i];$('content').innerHTML=`<div class="eyebrow">MODUL ${i+1} / ${modules.length}</div><h1>${m.title}</h1><p class="intro">Baca nota setiap subtopik, cuba contoh yang diberikan dan jawab kuiz untuk menguji pemahaman.</p><div class="topics">${m.topics.map((t,j)=>`<article class="topic"><h2>${t[0]} ${t[1]}</h2><p>${t[2]}</p><pre><code>${escapeHtml(t[3])}</code></pre>${i===0?richModule1[j]:''}</article>`).join('')}</div><section class="quiz"><h2>Kuiz Modul ${i+1}</h2><p>Jawab tiga soalan. Markah disimpan pada browser ini sahaja.</p><div id="quizbody"></div></section><div class="next"><button class="secondary" id="back">← Dashboard</button>${i<5?'<button class="primary" id="next">Modul seterusnya →</button>':''}</div>`;$('back').onclick=home;if(i<5)$('next').onclick=()=>show(i+1);renderQuiz(i);window.scrollTo(0,0);}
function escapeHtml(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function renderQuiz(i){$('quizbody').innerHTML=`<form id="quizform">${questions[i].map((q,j)=>`<fieldset><legend>${j+1}. ${q.q}</legend>${q.a.map((a,k)=>`<label class="answer"><input required type="radio" name="q${j}" value="${k}"> ${escapeHtml(a)}</label>`).join('')}</fieldset>`).join('')}<button class="primary" type="submit">Semak Markah</button></form><div id="result" role="status"></div>`;$('quizform').onsubmit=e=>{e.preventDefault();let data=new FormData(e.target),score=questions[i].reduce((n,q,j)=>n+(Number(data.get('q'+j))===q.correct?1:0),0);localStorage.setItem('pf-score-'+i,String(score));localStorage.setItem(key(i),'1');$('result').textContent=`Markah: ${score}/3 (${Math.round(score/3*100)}%). ${score===3?'Syabas! Semua jawapan betul.':'Semak semula nota dan cuba lagi.'}`;nav();};}
$('home').onclick=home;home();
