const modules=[
{title:'Problem Solving',topics:[['1.1','Demonstrate Programming Life Cycle (PLC)','The Programming Life Cycle includes problem definition, analysis, design, coding, testing, documentation and maintenance.','Example: For a grade calculator, identify inputs (marks), processing (calculate grade), and output (grade).'],['1.2','Construct problem solving concept','Break a problem into input, process and output (IPO). Use decomposition to solve smaller tasks.','IPO example: Input = two numbers; Process = addition; Output = sum.'],['1.3','Construct the different types of algorithms, pseudocode and flowcharts in solve problem','An algorithm is a finite series of instructions. Pseudocode uses structured plain language; flowcharts use standard symbols such as oval (start/end), parallelogram (input/output), rectangle (process), and diamond (decision).','START\nINPUT a, b\nsum ← a + b\nOUTPUT sum\nEND']]},
{title:'Introduction to Fundamentals of Programming',topics:[['2.1','Construct the C++ program basic structure','A basic C++ program uses #include, main(), statements and return 0.',' #include <iostream>\nusing namespace std;\nint main() {\n  cout << "Hello World";\n  return 0;\n}'],['2.2','Construct identifier and data types','Identifiers name variables and functions. Common C++ data types include int, double, char, bool and string.','int age = 18;\ndouble price = 12.50;\nchar grade = \'A\';\nbool passed = true;'],['2.3','Follow the basic step of computer program','Plan the solution, write source code, compile, run and test with different inputs.','Source code → Compiler → Executable → Run → Test'],['2.4','Follow instruction process of compiling and debugging process and errors in programming','Syntax errors violate language rules; runtime errors happen during execution; logic errors produce wrong results. Debugging identifies and corrects them.','Example syntax error: cout << "Hi"  // missing semicolon']]},
{title:'Program Elements',topics:[['3.1','Construct Identifiers','Use meaningful variable names. C++ identifiers cannot begin with a digit, contain spaces or use reserved keywords.','int totalMarks = 90;\n// 2marks and total marks are invalid identifiers'],['3.2','Construct operators and expressions','Arithmetic (+, -, *, /, %), relational (==, !=, >, <, >=, <=), and logical (&&, ||, !) operators form expressions.','int total = 10 + 5;\nbool eligible = (total >= 10) && (total < 20);'],['3.3','Construct input output statements','Use cin to read keyboard input and cout to display output.','int age;\ncout << "Enter age: ";\ncin >> age;\ncout << "Age: " << age;']]},
{title:'Program Control Structure',topics:[['4.1','Construct program control structure','Control structures determine execution order: sequence, selection and repetition.','Sequence: input → calculate → display'],['4.2','Construct selection control structures in problem solving','Use if, if-else or switch to choose actions based on conditions.','if (mark >= 50) {\n  cout << "Pass";\n} else {\n  cout << "Fail";\n}'],['4.3','Construct loops control structure in problem solving','Use for, while or do-while to repeat instructions. Ensure loop conditions eventually terminate.','for (int i = 1; i <= 5; i++) {\n  cout << i << endl;\n}']]},
{title:'Array',topics:[['5.1','Construct array in programming','An array stores multiple values of the same type under one name. C++ array indices start at 0.','int marks[3] = {70, 80, 90};\ncout << marks[0]; // 70\nfor (int i = 0; i < 3; i++) {\n  cout << marks[i] << endl;\n}']]},
{title:'Function',topics:[['6.1','Build functions in programming','A function groups reusable instructions. It may return a value or use void for no return value.','int add(int a, int b) {\n  return a + b;\n}'],['6.2','Build function prototype','A prototype declares a function name, return type and parameter types before its definition.','int add(int a, int b);\nint main() {\n  cout << add(2, 3);\n}\nint add(int a, int b) { return a + b; }'],['6.3','Build parameters passing techniques','Pass by value copies the argument; pass by reference (&) lets a function modify the original variable.','void increase(int &x) {\n  x++;\n}\nint number = 5;\nincrease(number); // number becomes 6']]}];
const questions=[
[{q:'Which stage normally comes before coding?',a:['Maintenance','Design','Deployment'],correct:1},{q:'Which flowchart symbol represents a decision?',a:['Diamond','Oval','Rectangle'],correct:0},{q:'IPO stands for...',a:['Input Process Output','Index Program Object','Internal Print Order'],correct:0}],
[{q:'What is the entry point of a typical C++ program?',a:['start()','main()','begin()'],correct:1},{q:'Which data type stores a whole number?',a:['int','char','bool'],correct:0},{q:'A missing semicolon is usually a...',a:['Logic error','Syntax error','Hardware error'],correct:1}],
[{q:'Which is a valid C++ identifier?',a:['2score','total_score','total score'],correct:1},{q:'Which operator checks equality?',a:['=','==','!='],correct:1},{q:'Which statement reads input?',a:['cin >> age;','cout << age;','return age;'],correct:0}],
[{q:'Which statement handles two alternative branches?',a:['if-else','include','return'],correct:0},{q:'Which loop is commonly used for a known number of repetitions?',a:['for','switch','if'],correct:0},{q:'Which is a selection structure?',a:['while','switch','for'],correct:1}],
[{q:'What is the first index of a C++ array?',a:['1','0','-1'],correct:1},{q:'How many values can int a[5] store?',a:['4','5','6'],correct:1},{q:'Which accesses the third array element?',a:['a[3]','a[2]','a(3)'],correct:1}],
[{q:'Which keyword declares a function with no return value?',a:['void','int','break'],correct:0},{q:'What does a function prototype provide?',a:['Declaration','Loop execution','Array index'],correct:0},{q:'Which syntax denotes a reference parameter?',a:['int x','int &x','int * x = 0'],correct:1}]
];
let selected=0;const $=id=>document.getElementById(id);const key=i=>'pf-progress-'+i;function completed(i){return localStorage.getItem(key(i))==='1'}
function nav(){ $('nav').innerHTML=modules.map((m,i)=>`<button class="navitem ${i===selected?'active':''}" data-module="${i}"><span>${String(i+1).padStart(2,'0')} · ${m.title}</span><span>${completed(i)?'✓':''}</span></button>`).join('');document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>show(+b.dataset.module));}
function home(){selected=-1;nav();$('content').innerHTML=`<div class="hero"><div class="eyebrow">E-LEARNING TVET · C++</div><h1>Programming Fundamentals</h1><p>Belajar asas pengaturcaraan secara berperingkat: penyelesaian masalah, struktur C++, elemen program, kawalan, array dan function.</p><button class="primary" id="start">Mula Belajar →</button></div><h2>Modul Pembelajaran</h2><div class="cards">${modules.map((m,i)=>`<button class="course" data-go="${i}"><span class="eyebrow">MODUL ${i+1} ${completed(i)?' · ✓ Selesai':''}</span><strong>${m.title}</strong><small>${m.topics.length} subtopik · Nota & kuiz</small><span class="arrow">Buka modul →</span></button>`).join('')}</div>`;$('start').onclick=()=>show(0);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(+b.dataset.go));}
function show(i){selected=i;nav();let m=modules[i];$('content').innerHTML=`<div class="eyebrow">MODUL ${i+1} / ${modules.length}</div><h1>${m.title}</h1><p class="intro">Baca nota setiap subtopik, cuba contoh yang diberikan dan jawab kuiz untuk menguji pemahaman.</p><div class="topics">${m.topics.map(t=>`<article class="topic"><h2>${t[0]} ${t[1]}</h2><p>${t[2]}</p><pre><code>${escapeHtml(t[3])}</code></pre></article>`).join('')}</div><section class="quiz"><h2>Kuiz Modul ${i+1}</h2><p>Jawab tiga soalan. Markah disimpan pada browser ini sahaja.</p><div id="quizbody"></div></section><div class="next"><button class="secondary" id="back">← Dashboard</button>${i<5?'<button class="primary" id="next">Modul seterusnya →</button>':''}</div>`;$('back').onclick=home;if(i<5)$('next').onclick=()=>show(i+1);renderQuiz(i);window.scrollTo(0,0);}
function escapeHtml(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function renderQuiz(i){$('quizbody').innerHTML=`<form id="quizform">${questions[i].map((q,j)=>`<fieldset><legend>${j+1}. ${q.q}</legend>${q.a.map((a,k)=>`<label class="answer"><input required type="radio" name="q${j}" value="${k}"> ${escapeHtml(a)}</label>`).join('')}</fieldset>`).join('')}<button class="primary" type="submit">Semak Markah</button></form><div id="result" role="status"></div>`;$('quizform').onsubmit=e=>{e.preventDefault();let data=new FormData(e.target),score=questions[i].reduce((n,q,j)=>n+(Number(data.get('q'+j))===q.correct?1:0),0);localStorage.setItem('pf-score-'+i,String(score));localStorage.setItem(key(i),'1');$('result').textContent=`Markah: ${score}/3 (${Math.round(score/3*100)}%). ${score===3?'Syabas! Semua jawapan betul.':'Semak semula nota dan cuba lagi.'}`;nav();};}
$('home').onclick=home;home();
